name: Use the Composite Action with Actions

on:
  workflow_dispatch:
  
env:
 REGISTRY_USERNAME: srinivasarao502
 IMAGE_NAME: myubuntu
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      # Uses the Composite Action
      - name: Login into DockerHub
        uses: srinivasarao-ceq/Composite_Actions/docker_build@main
        with:
          registry_username: ${{env.REGISTRY_USERNAME}}
          registry_password: ${{secrets.REGISTRY_PASSWORD}}
          
      - name: Build and push image into DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{env.REGISTRY_USERNAME}}/${{env.IMAGE_NAME}}:${{ github.run_number }}
