name: Call the reusable workflow
on:
  push

env:
  region: us-east-1
  
jobs:
  Run-terraform-scripts:
    runs-on: ubuntu-20.04
    steps:
      - name: call the terraform workflow
        uses: srinivasarao-ceq/Reusable_workflows/.github/workflows/Terraform.yml@main
        with:
          region: ${{env.region}}
        secrets:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    

    
