name: github with env
on:
#   push:
#     branches:
#       - "main"
#     paths-ignore:
#       - "README.md"
  workflow_dispatch:
env:
#   AWS_ACCESS_KEY: AKIAZ3CUIHQKATDFEJU2
#   AWS_SECRET_ACCESS_KEY: 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
#   AWS_REGION: eu-central-1
  GITHUB_SESSION: CEQ-bootcamp

jobs:
  ENV_SESSION:
    runs-on: ubuntu-latest
    steps:
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION}}
        env:
          AWS_ACCESS_KEY: AKIAZ3CUIHQKATDFEJU2
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: eu-central-1
    
  Print_ENV:
    runs-on: ubuntu-latest
    steps:   
      - name: To print the env values
        run: echo ${{ env.GITHUB_SESSION}}
         
